namespace ProductManagement.Api.DTOs.Products;

public sealed record ProductResponse(
    int Id,
    string ProductCode,
    string ProductName,
    int CategoryId,
    string CategoryCode,
    string CategoryName,
    bool CategoryIsActive,
    string Unit,
    decimal Price,
    decimal StockQuantity,
    string StockStatus,
    string? Description,
    bool IsActive,
    string? CreatedByUserId,
    string? CreatedByUsername,
    string? LastModifiedByUserId,
    string? LastModifiedByUsername,
    bool IsAdminProtected,
    bool IsDeleted,
    DateTime? DeletedAt,
    string? DeletedByUserId,
    string? DeletedByUsername,
    DateTime CreatedAt,
    DateTime? UpdatedAt);
